### ISSUE TITLE
Latest version throws error upon launch

### ISSUE THREAD

**Issue by rugabunda** [LesterLyu/where-to-buy-3080#4]
Just updated to the latest version, in linux, lubuntu having the following error:

```
:~/Downloads/where-to-buy-3080$ node index.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/lub/Downloads/where-to-buy-3080/jsdom/index.js:4:26)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

**Comment by rugabunda** [comment]
Also, upon NPM install I receive this: 
```

npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN where-to-buy-3080 No repository field.
npm WARN where-to-buy-3080 No license field.

```

**Comment by LesterLyu** [comment]
Latest Node.js is required.

**Comment by rugabunda** [comment]
I have that installed already. 10.19.0~dfsg-3ubuntu1. Are you using a beta/alpha/pre release?

**Comment by LesterLyu** [comment]
https://nodejs.org/en/

**Comment by rugabunda** [comment]
working now, tx!
